apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analysis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-analysis-service
  template:
    metadata:
      labels:
        app: ai-analysis-service
    spec:
      containers:
        - name: ai-analysis-service
          image: ai-analysis-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000